### ISSUE TITLE
accessTokenLifetime 不支持无限期

### ISSUE THREAD

**Issue by JokerLZD** [Azard/egg-oauth2-server#18]
config
```js
config.oAuth2Server = {
    debug: appInfo.env === 'local',
    grants: ['password'],
    accessTokenLifetime: null,
    refreshTokenLifetime: null
}
```
Error
```js
 nodejs.invalid_argument: Missing parameter: `accessTokenLifetime`
    at new InvalidArgumentError (/Volumes/Mac/Projects/Node/liubangback/node_modules/oauth2-server/lib/errors/invalid-argument-error.js:21:14)
    at new TokenHandler (/Volumes/Mac/Projects/Node/liubangback/node_modules/oauth2-server/lib/handlers/token-handler.js:43:11)
    at OAuth2Server.token (/Volumes/Mac/Projects/Node/liubangback/node_modules/oauth2-server/lib/server.js:74:10)
    at Object.<anonymous> (/Volumes/Mac/Projects/Node/liubangback/node_modules/egg-oauth2-server/lib/server.js:82:36)
    at Generator.next (<anonymous>)
    at Object.dispatch (/Volumes/Mac/Projects/Node/liubangback/node_modules/koa-router/lib/router.js:334:5)
    at dispatch.next (<anonymous>)
    at onFulfilled (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:65:19)
    at /Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:50:10)
    at Object.toPromise (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:118:63)
    at next (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:99:29)
    at onFulfilled (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:69:7)
    at /Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:50:10)
    at Object.toPromise (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:118:63)
    at next (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:99:29)
    at onFulfilled (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:69:7)
    at /Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
    at Object.co (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:50:10)
    at Object.toPromise (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:118:63)
    at next (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:99:29)
    at onFulfilled (/Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:69:7)
    at /Volumes/Mac/Projects/Node/liubangback/node_modules/co/index.js:54:5
    at new Promise (<anonymous>)
```

**Comment by Azard** [comment]
可以先设置一个超大的数字。
我先记一下，下次可以加上这个功能。

**Comment by JokerLZD** [comment]
@Azard  OK 😆

**Comment by rexleimo** [comment]
这个是refreshTokenLifetime是按秒还是 毫秒

**Comment by Azard** [comment]
@rainbowMorelhahahah 毫秒吧
