### ISSUE TITLE
Issue with eggjs 2.0

### ISSUE THREAD

**Issue by ole3021** [Azard/egg-oauth2-server#20]
在 egg.js 中使用在获取token的saveToken之后会报如下错误
```
egg: 2.0.0 
node: 8.9.0
os: mac 10.13.1
```

```
2017-11-29 03:22:00,577 ERROR 58549 [-/::1/-/126ms POST /login] nodejs.TypeError: undefined is not a function
    at Object.<anonymous> (/Users/ole3021/ducklab/ci-backend/node_modules/egg-oauth2-server/lib/server.js:102:20)
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/ole3021/ducklab/ci-backend/node_modules/co/index.js:65:19)
    at <anonymous>
```

经初步排查错误代码发生在`lib/server.js`中第101行的`if (token) { yield* next; }`, 其中next不是可yield的generator函数，而是ctx对象。

修正方法可使用`if(token) ctx.body = token` 来替代(初步解决方法)

问题应该是对egg新版本的适配问题， 刚刚发现， 有时间的话会提pr，另外希望可以尽快适配并做好测试。：）

**Comment by Azard** [comment]
感谢反馈，我这几天有空适配下

**Comment by jojowwbb** [comment]
同样遇到、请问什么时候可以更新呢！

**Comment by Azard** [comment]
@daoxiaozhang 我今天上午搞一下。

**Comment by Azard** [comment]
@ole3021 @daoxiaozhang 已经适配 egg 2.x 了
